sudo: false
language: python
cache: pip
python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
notifications:
  email: false
# command to install dependencies
install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install -r requirements.txt"
# command to run nosetests
script: nosetests labrat/tests/ --verbosity=3